# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=200)),
                ('ip_address', models.CharField(max_length=15, unique=True)),
                ('port', models.IntegerField(default=13000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=200)),
                ('ip_address', models.CharField(max_length=15, unique=True)),
                ('port', models.IntegerField(default=13000)),
                ('probing_interval', models.IntegerField(default=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonitoredProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('monitored_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acquisition_presentation_server.MonitoredProperties')),
            ],
        ),
        migrations.CreateModel(
            name='PendingClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=200)),
                ('ip_address', models.CharField(max_length=15, unique=True)),
                ('port', models.IntegerField(default=13000)),
                ('monitored_properties', models.ManyToManyField(to='acquisition_presentation_server.MonitoredProperties')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='monitoredproperties',
            unique_together=set([('name', 'type')]),
        ),
        migrations.AddField(
            model_name='client',
            name='monitored_properties',
            field=models.ManyToManyField(to='acquisition_presentation_server.MonitoredProperties'),
        ),
        migrations.AddField(
            model_name='blockedclient',
            name='monitored_properties',
            field=models.ManyToManyField(to='acquisition_presentation_server.MonitoredProperties'),
        ),
    ]
