# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=200, unique=True)),
                ('ip_address', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=200, unique=True)),
                ('ip_address', models.CharField(max_length=15, unique=True)),
                ('probing_interval', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonitoredProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitored_properties', models.CharField(choices=[('cpu', 'cpu_usage'), ('ram', 'ram_usage'), ('dsk', 'disk_usage')], max_length=3)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acquisition_presentation_server.Client')),
            ],
        ),
        migrations.CreateModel(
            name='PendingClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=200, unique=True)),
                ('ip_address', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
