# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=200)),
                ('ip_address', models.CharField(max_length=15)),
                ('port', models.IntegerField(default=13000)),
                ('probing_interval', models.IntegerField(default=10)),
                ('is_configured', models.BooleanField(default=False)),
                ('last_update', models.IntegerField(default=-1)),
                ('state', models.IntegerField(db_index=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoredProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('monitored', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_properties', to='acquisition_presentation_server.ClientBase')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='clientbase',
            unique_together=set([('ip_address', 'port')]),
        ),
        migrations.CreateModel(
            name='BlockedClient',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('acquisition_presentation_server.clientbase',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('acquisition_presentation_server.clientbase',),
        ),
        migrations.CreateModel(
            name='PendingClient',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('acquisition_presentation_server.clientbase',),
        ),
    ]
