# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition_presentation_server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoringdata',
            name='monitored_property',
        ),
        migrations.AddField(
            model_name='client',
            name='_rrd_database_location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='MonitoringData',
        ),
    ]
