# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition_presentation_server', '0002_auto_20161025_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='_rrd_database_location',
        ),
    ]
