# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition_presentation_server', '0003_remove_client__rrd_database_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_configured',
            field=models.BooleanField(default=False),
        ),
    ]
